name: 'Transcode'
id: 'transcode-oneshot'

stages:
  - transcode:
      job: transcode/maria
      data:
        - host: '%mysql_host%'
        - port: '%mysql_port%'
        - user: '%mysql_user%'
        - password: '%mysql_password%'