version: '3'

services:
  redis:
    image: redis:3.2
    volumes:
      - .data/redis:/data

  app:
    build: .
    ports:
      - 8090:${API_PORT}
    volumes:
      - ./:/var/app
    links:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_PORT: ${API_PORT}
      CONCERTO_URL: 'http://localhost:8888/api'