version: '3'

services:
  redis:
    image: redis:4.0.2
    volumes:
      - ${STORAGE}/redis:/data

  mongodb:
    image: mongo:3
    volumes:
      - ${STORAGE}/mongodb:/data/db

  app:
    build: .
    ports:
      - 8090:8080 # Workflow
      - 8091:4001 # Arena
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
      QUEUE_HOST_ID: Scrapper
      QUEUE_NAME: global
      MONGO_HOST: mongodb
      MONGO_PORT: ${MONGO_PORT}
    links:
      - redis
      - mongodb